# Generated by Django 4.0.2 on 2022-02-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfa_implmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=12)),
                ('accountNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountnumber', to='mfa_implmentation.userinformation')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userName', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
