# Generated by Django 4.0.3 on 2022-03-06 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfa_implmentation', '0002_useraccountbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMfaSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=50)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
