# Generated by Django 4.0.3 on 2022-03-29 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mfa_implmentation', '0003_usermfasecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='User3MfaCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backupCode1', models.CharField(max_length=7)),
                ('backupCode2', models.CharField(max_length=7)),
                ('backupCode3', models.CharField(max_length=7)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
