# Generated by Django 4.0.2 on 2022-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_implmentation', '0005_user3mfacodes_potp_userinformation_pnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('accountNumber', models.CharField(max_length=11)),
                ('transactionAmount', models.CharField(max_length=10)),
                ('transactionType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='pnumber',
            field=models.CharField(max_length=12),
        ),
    ]
